let e = require;let t = module;
    "use strict";

    cc._RF.push(t, "c0850mKpShNd5gk5QykzOvX", "FModeConfig2");
    t.exports = {
      json: {
        arr: [{
          tableInfo: {
            tableID: 11,
            sID: 11,
            name: "username-1",
            time: 1573359932758,
            balls: [{
              ballID: 200,
              ballType: 2,
              x: 223,
              y: 8,
              tx1: 0,
              tx2: 0,
              ballMatIdx: 2,
              p1: 0,
              p2: 0,
              p3: 0
            }, {
              ballID: 201,
              ballType: 2,
              x: 121,
              y: 3,
              tx1: 0,
              tx2: 0,
              ballMatIdx: 3,
              p1: 0,
              p2: 0,
              p3: 0
            }, {
              ballID: 100,
              ballType: 1,
              x: 11,
              y: -4,
              tx1: 0,
              tx2: 0,
              ballMatIdx: 0,
              p1: 0,
              p2: 0,
              p3: 0
            }],
            condition: {
              type: 1,
              cdBalls: [{
                ballMatIdx: 2,
                ballType: 2,
                ballNum: 0,
                p1: 0,
                p2: 0
              }, {
                ballMatIdx: 3,
                ballType: 2,
                ballNum: 0,
                p1: 0,
                p2: 0
              }],
              lHallID: [],
              ganNum: 2,
              p1: 0,
              p2: 0
            },
            cue: {
              cueID: 0,
              Mat: 0,
              p1: 0,
              p2: 0
            },
            isPass: 0,
            tableMat: 0,
            color: "6",
            particle: "2",
            p1: 0,
            p2: 0,
            p3: 0
          },
          mv: {
            balls: [{
              ballID: 200,
              ballType: 2,
              ballMatIdx: 2,
              x: 223,
              y: 8
            }, {
              ballID: 201,
              ballType: 2,
              ballMatIdx: 3,
              x: 121,
              y: 3
            }, {
              ballID: 100,
              ballType: 1,
              ballMatIdx: 0,
              x: 11,
              y: -4
            }],
            cues: [{
              hit: {
                rad: -311267,
                power: 89,
                time: 7052,
                radAngle: 0,
                radVx: 0,
                radVy: 0
              },
              moves: [{
                ballID: 100,
                time: 2004,
                x: 11,
                y: -4,
                vx: 2577.5,
                vy: 74.5
              }, {
                ballID: 100,
                time: 2033,
                x: 53.2,
                y: -2.8,
                vx: 2535.2,
                vy: 73.3
              }, {
                ballID: 100,
                time: 2049,
                x: 92.1,
                y: -2.1,
                vx: 186.1,
                vy: -299.9
              }, {
                ballID: 201,
                time: 2049,
                x: 123.7,
                y: 3.4,
                vx: 2307.6,
                vy: 371.9
              }, {
                ballID: 201,
                time: 2066,
                x: 161.7,
                y: 9.5,
                vx: 2280.9,
                vy: 367.6
              }, {
                ballID: 201,
                time: 2082,
                x: 195.2,
                y: 16.6,
                vx: 411.8,
                vy: 808.4
              }, {
                ballID: 200,
                time: 2082,
                x: 227,
                y: 7,
                vx: 1842.7,
                vy: -445
              }, {
                ballID: 200,
                time: 2098,
                x: 257.4,
                y: -.4,
                vx: 1821.5,
                vy: -439.9
              }, {
                ballID: 201,
                time: 2198,
                x: 239,
                y: 106.6,
                vx: -303.9,
                vy: 745.3
              }, {
                ballID: 201,
                time: 2865,
                x: 77.9,
                y: 489.3,
                vx: -191.1,
                vy: -375
              }, {
                ballID: 100,
                time: 3648,
                x: 238.9,
                y: -240.5,
                vx: -33.9,
                vy: -61.4
              }, {
                ballID: 100,
                time: 5365,
                x: 211.2,
                y: -290.7,
                vx: 0,
                vy: 0
              }, {
                ballID: 201,
                time: 7817,
                x: -186.3,
                y: -29.2,
                vx: 0,
                vy: 0
              }],
              des: [{
                ballID: 200,
                time: 2633
              }]
            }, {
              hit: {
                rad: -58719,
                power: 92,
                time: 17142,
                radAngle: 0,
                radVx: 0,
                radVy: 0
              },
              moves: [{
                ballID: 100,
                time: 12098,
                x: 211.2,
                y: -290.7,
                vx: -2219.1,
                vy: 1476.7
              }, {
                ballID: 100,
                time: 12117,
                x: 174.8,
                y: -266.5,
                vx: -2182.7,
                vy: 1452.5
              }, {
                ballID: 100,
                time: 12315,
                x: -160.2,
                y: -40.3,
                vx: 13.1,
                vy: 204.9
              }, {
                ballID: 201,
                time: 12315,
                x: -214.1,
                y: -13.9,
                vx: -1833,
                vy: 1006
              }, {
                ballID: 201,
                time: 12334,
                x: -244.3,
                y: 2.7,
                vx: -1811.9,
                vy: 994.4
              }, {
                ballID: 201,
                time: 12348,
                x: -274.1,
                y: 11.6,
                vx: -1791,
                vy: -786.5
              }, {
                ballID: 100,
                time: 15116,
                x: -147.9,
                y: 151.9,
                vx: 0,
                vy: 0
              }],
              des: [{
                ballID: 201,
                time: 12882
              }]
            }]
          },
          mvCompress: 0,
          time: "2019-11-30 12:48:53"
        }, {
          tableInfo: {
            tableID: 12,
            sID: 12,
            name: "username-1",
            time: 1573359932758,
            balls: [{
              ballID: 200,
              ballType: 2,
              x: 221,
              y: -2,
              tx1: 0,
              tx2: 0,
              ballMatIdx: 2,
              p1: 0,
              p2: 0,
              p3: 0
            }, {
              ballID: 201,
              ballType: 2,
              x: 130,
              y: -4,
              tx1: 0,
              tx2: 0,
              ballMatIdx: 3,
              p1: 0,
              p2: 0,
              p3: 0
            }, {
              ballID: 100,
              ballType: 1,
              x: 11,
              y: -4,
              tx1: 0,
              tx2: 0,
              ballMatIdx: 0,
              p1: 0,
              p2: 0,
              p3: 0
            }],
            condition: {
              type: 1,
              cdBalls: [{
                ballMatIdx: 2,
                ballType: 2,
                ballNum: 0,
                p1: 0,
                p2: 0
              }, {
                ballMatIdx: 3,
                ballType: 2,
                ballNum: 0,
                p1: 0,
                p2: 0
              }],
              lHallID: [],
              ganNum: 1,
              p1: 0,
              p2: 0
            },
            cue: {
              cueID: 0,
              Mat: 0,
              p1: 0,
              p2: 0
            },
            isPass: 0,
            tableMat: 0,
            color: "6",
            particle: "2",
            p1: 0,
            p2: 0,
            p3: 0
          },
          mv: {
            balls: [{
              ballID: 200,
              ballType: 2,
              ballMatIdx: 2,
              x: 221,
              y: -2
            }, {
              ballID: 201,
              ballType: 2,
              ballMatIdx: 3,
              x: 130,
              y: -4
            }, {
              ballID: 100,
              ballType: 1,
              ballMatIdx: 0,
              x: 11,
              y: -4
            }],
            cues: [{
              hit: {
                rad: -314657,
                power: 37,
                time: 4770,
                radAngle: 0,
                radVx: 0,
                radVy: 0
              },
              moves: [{
                ballID: 100,
                time: 2002,
                x: 11,
                y: -4,
                vx: 1071.9,
                vy: -5.4
              }, {
                ballID: 100,
                time: 2017,
                x: 28.5,
                y: -4.1,
                vx: 1054.4,
                vy: -5.3
              }, {
                ballID: 100,
                time: 2102,
                x: 101.6,
                y: -4.7,
                vx: 97.3,
                vy: -18.2
              }, {
                ballID: 201,
                time: 2102,
                x: 140.5,
                y: -3.9,
                vx: 873.4,
                vy: 13.3
              }, {
                ballID: 201,
                time: 2119,
                x: 154.9,
                y: -3.7,
                vx: 863.3,
                vy: 13.1
              }, {
                ballID: 201,
                time: 2168,
                x: 192,
                y: -3.2,
                vx: 83.9,
                vy: -14.4
              }, {
                ballID: 200,
                time: 2168,
                x: 226,
                y: -1.9,
                vx: 749.8,
                vy: 27.1
              }, {
                ballID: 200,
                time: 2185,
                x: 238.3,
                y: -1.4,
                vx: 741.2,
                vy: 26.7
              }, {
                ballID: 100,
                time: 4202,
                x: 186.4,
                y: -20.5,
                vx: 0,
                vy: 0
              }],
              des: [{
                ballID: 200,
                time: 2719
              }, {
                ballID: 201,
                time: 3569
              }]
            }]
          },
          mvCompress: 0,
          time: "2019-11-30 12:51:52"
        }, {
          tableInfo: {
            tableID: 13,
            sID: 13,
            name: "username-1",
            time: 1573359932758,
            balls: [{
              ballID: 200,
              ballType: 2,
              x: 211,
              y: 474,
              tx1: 0,
              tx2: 0,
              ballMatIdx: 2,
              p1: 0,
              p2: 0,
              p3: 0
            }, {
              ballID: 201,
              ballType: 2,
              x: 150,
              y: 307,
              tx1: 0,
              tx2: 0,
              ballMatIdx: 3,
              p1: 0,
              p2: 0,
              p3: 0
            }, {
              ballID: 100,
              ballType: 1,
              x: 11,
              y: -4,
              tx1: 0,
              tx2: 0,
              ballMatIdx: 0,
              p1: 0,
              p2: 0,
              p3: 0
            }],
            condition: {
              type: 1,
              cdBalls: [{
                ballMatIdx: 2,
                ballType: 2,
                ballNum: 0,
                p1: 0,
                p2: 0
              }, {
                ballMatIdx: 3,
                ballType: 2,
                ballNum: 0,
                p1: 0,
                p2: 0
              }],
              lHallID: [],
              ganNum: 2,
              p1: 0,
              p2: 0
            },
            cue: {
              cueID: 0,
              Mat: 0,
              p1: 0,
              p2: 0
            },
            isPass: 0,
            tableMat: 0,
            color: "6",
            particle: "2",
            p1: 0,
            p2: 0,
            p3: 0
          },
          mv: {
            balls: [{
              ballID: 200,
              ballType: 2,
              ballMatIdx: 2,
              x: 211,
              y: 474
            }, {
              ballID: 201,
              ballType: 2,
              ballMatIdx: 3,
              x: 150,
              y: 307
            }, {
              ballID: 100,
              ballType: 1,
              ballMatIdx: 0,
              x: 11,
              y: -4
            }],
            cues: [{
              hit: {
                rad: -200478,
                power: 76,
                time: 5418,
                radAngle: 0,
                radVx: 0,
                radVy: 0
              },
              moves: [{
                ballID: 100,
                time: 2015,
                x: 11,
                y: -4,
                vx: 925.8,
                vy: 1997.8
              }, {
                ballID: 100,
                time: 2031,
                x: 26.1,
                y: 28.7,
                vx: 910.6,
                vy: 1965.1
              }, {
                ballID: 100,
                time: 2182,
                x: 146.2,
                y: 279.8,
                vx: 335.7,
                vy: 96.9
              }, {
                ballID: 201,
                time: 2182,
                x: 155.7,
                y: 327.5,
                vx: 449,
                vy: 1596.4
              }, {
                ballID: 201,
                time: 2198,
                x: 163.1,
                y: 353.8,
                vx: 443.9,
                vy: 1578
              }, {
                ballID: 200,
                time: 2265,
                x: 213,
                y: 476.1,
                vx: 855.4,
                vy: 910.4
              }, {
                ballID: 201,
                time: 2265,
                x: 189.8,
                y: 453.8,
                vx: -431.7,
                vy: 596
              }, {
                ballID: 200,
                time: 2280,
                x: 227.1,
                y: 491.1,
                vx: 845.5,
                vy: 899.9
              }, {
                ballID: 200,
                time: 2298,
                x: 243.6,
                y: 502.3,
                vx: 1092.1,
                vy: 524.5
              }, {
                ballID: 201,
                time: 2348,
                x: 155.1,
                y: 489.5,
                vx: -407.4,
                vy: -450
              }, {
                ballID: 100,
                time: 2513,
                x: 239.3,
                y: 307.1,
                vx: -183.4,
                vy: 69.6
              }, {
                ballID: 201,
                time: 3996,
                x: -238.4,
                y: 50.5,
                vx: 103.3,
                vy: -142.8
              }, {
                ballID: 100,
                time: 5264,
                x: 68,
                y: 372.2,
                vx: 0,
                vy: 0
              }, {
                ballID: 201,
                time: 7698,
                x: -102,
                y: -137.8,
                vx: 0,
                vy: 0
              }],
              des: [{
                ballID: 200,
                time: 2831
              }]
            }, {
              hit: {
                rad: 125214,
                power: 52,
                time: 25942,
                radAngle: 0,
                radVx: 0,
                radVy: 0
              },
              moves: [{
                ballID: 100,
                time: 22532,
                x: 68,
                y: 372.2,
                vx: -472.1,
                vy: -1430.8
              }, {
                ballID: 100,
                time: 22548,
                x: 60.2,
                y: 348.8,
                vx: -464.3,
                vy: -1407.4
              }, {
                ballID: 100,
                time: 22948,
                x: -91.2,
                y: -110.6,
                vx: 15.1,
                vy: -112.9
              }, {
                ballID: 201,
                time: 22948,
                x: -102.6,
                y: -139.3,
                vx: -327.4,
                vy: -833.7
              }, {
                ballID: 201,
                time: 22963,
                x: -108,
                y: -153.1,
                vx: -323.6,
                vy: -824.1
              }, {
                ballID: 100,
                time: 25147,
                x: -77.8,
                y: -210.7,
                vx: 0,
                vy: 0
              }],
              des: [{
                ballID: 201,
                time: 23982
              }]
            }]
          },
          mvCompress: 0,
          time: "2019-11-30 18:19:41"
        }, {
          tableInfo: {
            tableID: 14,
            sID: 14,
            name: "username-1",
            time: 1573359932758,
            balls: [{
              ballID: 200,
              ballType: 2,
              x: 222,
              y: 464,
              tx1: 0,
              tx2: 0,
              ballMatIdx: 2,
              p1: 0,
              p2: 0,
              p3: 0
            }, {
              ballID: 201,
              ballType: 2,
              x: 181,
              y: 370,
              tx1: 0,
              tx2: 0,
              ballMatIdx: 3,
              p1: 0,
              p2: 0,
              p3: 0
            }, {
              ballID: 100,
              ballType: 1,
              x: 11,
              y: -4,
              tx1: 0,
              tx2: 0,
              ballMatIdx: 0,
              p1: 0,
              p2: 0,
              p3: 0
            }],
            condition: {
              type: 1,
              cdBalls: [{
                ballMatIdx: 2,
                ballType: 2,
                ballNum: 0,
                p1: 0,
                p2: 0
              }, {
                ballMatIdx: 3,
                ballType: 2,
                ballNum: 0,
                p1: 0,
                p2: 0
              }],
              lHallID: [],
              ganNum: 1,
              p1: 0,
              p2: 0
            },
            cue: {
              cueID: 0,
              Mat: 0,
              p1: 0,
              p2: 0
            },
            isPass: 0,
            tableMat: 0,
            color: "6",
            particle: "2",
            p1: 0,
            p2: 0,
            p3: 0
          },
          mv: {
            balls: [{
              ballID: 200,
              ballType: 2,
              ballMatIdx: 2,
              x: 222,
              y: 464
            }, {
              ballID: 201,
              ballType: 2,
              ballMatIdx: 3,
              x: 181,
              y: 370
            }, {
              ballID: 100,
              ballType: 1,
              ballMatIdx: 0,
              x: 11,
              y: -4
            }],
            cues: [{
              hit: {
                rad: -199842,
                power: 92,
                time: 4330,
                radAngle: 0,
                radVx: 0,
                radVy: 0
              },
              moves: [{
                ballID: 100,
                time: 2010,
                x: 11,
                y: -4,
                vx: 1105.4,
                vy: 2425.5
              }, {
                ballID: 100,
                time: 2024,
                x: 29.1,
                y: 35.7,
                vx: 1087.2,
                vy: 2385.7
              }, {
                ballID: 100,
                time: 2191,
                x: 169.8,
                y: 343.7,
                vx: 65.1,
                vy: 70
              }, {
                ballID: 201,
                time: 2191,
                x: 190.5,
                y: 391.7,
                vx: 871.8,
                vy: 1985.9
              }, {
                ballID: 201,
                time: 2207,
                x: 204.9,
                y: 424.4,
                vx: 861.7,
                vy: 1963
              }, {
                ballID: 201,
                time: 2225,
                x: 211.3,
                y: 438.8,
                vx: 99.8,
                vy: 187.7
              }, {
                ballID: 200,
                time: 2226,
                x: 229.7,
                y: 482,
                vx: 752,
                vy: 1752.6
              }, {
                ballID: 200,
                time: 2241,
                x: 242.1,
                y: 510.8,
                vx: 743.3,
                vy: 1732.3
              }, {
                ballID: 100,
                time: 4227,
                x: 226.3,
                y: 404.5,
                vx: 0,
                vy: 0
              }],
              des: [{
                ballID: 200,
                time: 2760
              }, {
                ballID: 201,
                time: 3110
              }]
            }]
          },
          mvCompress: 0,
          time: "2019-11-30 18:25:27"
        }, {
          tableInfo: {
            tableID: 15,
            sID: 15,
            name: "username-1",
            time: 1573359932758,
            balls: [{
              ballID: 200,
              ballType: 2,
              x: 225,
              y: -457,
              tx1: 0,
              tx2: 0,
              ballMatIdx: 2,
              p1: 0,
              p2: 0,
              p3: 0
            }, {
              ballID: 201,
              ballType: 2,
              x: 181,
              y: -352,
              tx1: 0,
              tx2: 0,
              ballMatIdx: 3,
              p1: 0,
              p2: 0,
              p3: 0
            }, {
              ballID: 100,
              ballType: 1,
              x: 11,
              y: -4,
              tx1: 0,
              tx2: 0,
              ballMatIdx: 0,
              p1: 0,
              p2: 0,
              p3: 0
            }],
            condition: {
              type: 1,
              cdBalls: [{
                ballMatIdx: 2,
                ballType: 2,
                ballNum: 0,
                p1: 0,
                p2: 0
              }, {
                ballMatIdx: 3,
                ballType: 2,
                ballNum: 0,
                p1: 0,
                p2: 0
              }],
              lHallID: [],
              ganNum: 2,
              p1: 0,
              p2: 0
            },
            cue: {
              cueID: 0,
              Mat: 0,
              p1: 0,
              p2: 0
            },
            isPass: 0,
            tableMat: 0,
            color: "6",
            particle: "2",
            p1: 0,
            p2: 0,
            p3: 0
          },
          mv: {
            balls: [{
              ballID: 200,
              ballType: 2,
              ballMatIdx: 2,
              x: 225,
              y: -457
            }, {
              ballID: 201,
              ballType: 2,
              ballMatIdx: 3,
              x: 181,
              y: -352
            }, {
              ballID: 100,
              ballType: 1,
              ballMatIdx: 0,
              x: 11,
              y: -4
            }],
            cues: [{
              hit: {
                rad: 202489,
                power: 71,
                time: 9811,
                radAngle: 0,
                radVx: 0,
                radVy: 0
              },
              moves: [{
                ballID: 100,
                time: 2010,
                x: 11,
                y: -4,
                vx: 902.3,
                vy: -1848.7
              }, {
                ballID: 100,
                time: 2211,
                x: 168.4,
                y: -326.7,
                vx: 68.3,
                vy: -154.4
              }, {
                ballID: 201,
                time: 2211,
                x: 185.8,
                y: -362,
                vx: 671.6,
                vy: -1361.7
              }, {
                ballID: 201,
                time: 2227,
                x: 196.9,
                y: -384.4,
                vx: 663.8,
                vy: -1346
              }, {
                ballID: 201,
                time: 2294,
                x: 224.8,
                y: -429.3,
                vx: 368.6,
                vy: -62.9
              }, {
                ballID: 200,
                time: 2294,
                x: 229.5,
                y: -477.9,
                vx: 272.4,
                vy: -1237.1
              }, {
                ballID: 200,
                time: 2310,
                x: 234,
                y: -498.3,
                vx: 269.3,
                vy: -1222.8
              }, {
                ballID: 200,
                time: 2327,
                x: 253,
                y: -499.6,
                vx: 1139.6,
                vy: -78.5
              }, {
                ballID: 201,
                time: 2363,
                x: 237.7,
                y: -432.4,
                vx: -284.9,
                vy: -60.8
              }, {
                ballID: 201,
                time: 4193,
                x: -55.7,
                y: -494.7,
                vx: -79.6,
                vy: 0
              }, {
                ballID: 100,
                time: 4859,
                x: 231.6,
                y: -469.4,
                vx: 0,
                vy: 0
              }, {
                ballID: 201,
                time: 6760,
                x: -150,
                y: -494.7,
                vx: 0,
                vy: 0
              }],
              des: [{
                ballID: 200,
                time: 2862
              }]
            }, {
              hit: {
                rad: 7214,
                power: 40,
                time: 18907,
                radAngle: 0,
                radVx: 0,
                radVy: 0
              },
              moves: [{
                ballID: 100,
                time: 11102,
                x: 231.6,
                y: -469.4,
                vx: -1156,
                vy: -83.6
              }, {
                ballID: 100,
                time: 11111,
                x: 212.6,
                y: -470.8,
                vx: -1137,
                vy: -82.2
              }, {
                ballID: 100,
                time: 11493,
                x: -121.9,
                y: -494.3,
                vx: -79.2,
                vy: 28.5
              }, {
                ballID: 201,
                time: 11495,
                x: -162.1,
                y: -494.6,
                vx: -711.3,
                vy: 4.9
              }, {
                ballID: 100,
                time: 13411,
                x: -189,
                y: -470.1,
                vx: 0,
                vy: 0
              }],
              des: [{
                ballID: 201,
                time: 12145
              }]
            }]
          },
          mvCompress: 0,
          time: "2019-11-30 18:59:12"
        }, {
          tableInfo: {
            tableID: 16,
            sID: 16,
            name: "username-1",
            time: 1573359932758,
            balls: [{
              ballID: 200,
              ballType: 2,
              x: 227,
              y: -480,
              tx1: 0,
              tx2: 0,
              ballMatIdx: 2,
              p1: 0,
              p2: 0,
              p3: 0
            }, {
              ballID: 201,
              ballType: 2,
              x: 208,
              y: -446,
              tx1: 0,
              tx2: 0,
              ballMatIdx: 3,
              p1: 0,
              p2: 0,
              p3: 0
            }, {
              ballID: 100,
              ballType: 1,
              x: 11,
              y: -4,
              tx1: 0,
              tx2: 0,
              ballMatIdx: 0,
              p1: 0,
              p2: 0,
              p3: 0
            }],
            condition: {
              type: 1,
              cdBalls: [{
                ballMatIdx: 2,
                ballType: 2,
                ballNum: 0,
                p1: 0,
                p2: 0
              }, {
                ballMatIdx: 3,
                ballType: 2,
                ballNum: 0,
                p1: 0,
                p2: 0
              }],
              lHallID: [],
              ganNum: 1,
              p1: 0,
              p2: 0
            },
            cue: {
              cueID: 0,
              Mat: 0,
              p1: 0,
              p2: 0
            },
            isPass: 0,
            tableMat: 0,
            color: "6",
            particle: "2",
            p1: 0,
            p2: 0,
            p3: 0
          },
          mv: {
            balls: [{
              ballID: 200,
              ballType: 2,
              ballMatIdx: 2,
              x: 227,
              y: -480
            }, {
              ballID: 201,
              ballType: 2,
              ballMatIdx: 3,
              x: 208,
              y: -446
            }, {
              ballID: 100,
              ballType: 1,
              ballMatIdx: 0,
              x: 11,
              y: -4
            }],
            cues: [{
              hit: {
                rad: 198391,
                power: 45,
                time: 4315,
                radAngle: 0,
                radVx: 0,
                radVy: 0
              },
              moves: [{
                ballID: 100,
                time: 2009,
                x: 11,
                y: -4,
                vx: 523.4,
                vy: -1194.2
              }, {
                ballID: 100,
                time: 2032,
                x: 19.5,
                y: -23.6,
                vx: 514.8,
                vy: -1174.6
              }, {
                ballID: 100,
                time: 2449,
                x: 193.4,
                y: -420.5,
                vx: -33.7,
                vy: -116.1
              }, {
                ballID: 201,
                time: 2449,
                x: 208.4,
                y: -446.8,
                vx: 374.1,
                vy: -661
              }, {
                ballID: 201,
                time: 2465,
                x: 212.8,
                y: -454.6,
                vx: 41.3,
                vy: -63
              }, {
                ballID: 200,
                time: 2465,
                x: 228.6,
                y: -483.1,
                vx: 328.5,
                vy: -590.5
              }, {
                ballID: 200,
                time: 2482,
                x: 234.1,
                y: -492.8,
                vx: 324.7,
                vy: -583.7
              }, {
                ballID: 100,
                time: 3515,
                x: 171.7,
                y: -494.5,
                vx: -11.9,
                vy: 20.4
              }, {
                ballID: 100,
                time: 4135,
                x: 166.2,
                y: -485.2,
                vx: 0,
                vy: 0
              }],
              des: [{
                ballID: 200,
                time: 3015
              }, {
                ballID: 201,
                time: 3983
              }]
            }]
          },
          mvCompress: 0,
          time: "2019-11-30 19:28:17"
        }, {
          tableInfo: {
            tableID: 17,
            sID: 17,
            name: "username-1",
            time: 1573359932758,
            balls: [{
              ballID: 200,
              ballType: 2,
              x: 158,
              y: -338,
              tx1: 0,
              tx2: 0,
              ballMatIdx: 3,
              p1: 0,
              p2: 0,
              p3: 0
            }, {
              ballID: 201,
              ballType: 2,
              x: 229,
              y: -482,
              tx1: 0,
              tx2: 0,
              ballMatIdx: 2,
              p1: 0,
              p2: 0,
              p3: 0
            }, {
              ballID: 100,
              ballType: 1,
              x: 11,
              y: -4,
              tx1: 0,
              tx2: 0,
              ballMatIdx: 0,
              p1: 0,
              p2: 0,
              p3: 0
            }],
            condition: {
              type: 1,
              cdBalls: [{
                ballMatIdx: 3,
                ballType: 2,
                ballNum: 0,
                p1: 0,
                p2: 0
              }, {
                ballMatIdx: 2,
                ballType: 2,
                ballNum: 0,
                p1: 0,
                p2: 0
              }],
              lHallID: [],
              ganNum: 1,
              p1: 0,
              p2: 0
            },
            cue: {
              cueID: 0,
              Mat: 0,
              p1: 0,
              p2: 0
            },
            isPass: 0,
            tableMat: 0,
            color: "6",
            particle: "2",
            p1: 0,
            p2: 0,
            p3: 0
          },
          mv: {
            balls: [{
              ballID: 200,
              ballType: 2,
              ballMatIdx: 3,
              x: 158,
              y: -338
            }, {
              ballID: 201,
              ballType: 2,
              ballMatIdx: 2,
              x: 229,
              y: -482
            }, {
              ballID: 100,
              ballType: 1,
              ballMatIdx: 0,
              x: 11,
              y: -4
            }],
            cues: [{
              hit: {
                rad: 198226,
                power: 71,
                time: 12012,
                radAngle: 34,
                radVx: -.004571428571428744,
                radVy: .4688095238095235
              },
              moves: [{
                ballID: 100,
                time: 2006,
                x: 11,
                y: -4,
                vx: 682,
                vy: -1563.1
              }, {
                ballID: 100,
                time: 2019,
                x: 22.1,
                y: -29.7,
                vx: 670.9,
                vy: -1537.5
              }, {
                ballID: 100,
                time: 2219,
                x: 144.9,
                y: -314.1,
                vx: 0,
                vy: -179.3
              }, {
                ballID: 200,
                time: 2219,
                x: 166.9,
                y: -356.1,
                vx: 641,
                vy: -1296.2
              }, {
                ballID: 100,
                time: 2236,
                x: 144.9,
                y: -317.2,
                vx: 0,
                vy: -186.1
              }, {
                ballID: 200,
                time: 2236,
                x: 177.4,
                y: -377.5,
                vx: 633.6,
                vy: -1281.2
              }, {
                ballID: 100,
                time: 2253,
                x: 144.9,
                y: -320.4,
                vx: 0,
                vy: -192.4
              }, {
                ballID: 100,
                time: 2269,
                x: 144.9,
                y: -323.7,
                vx: -.1,
                vy: -198.2
              }, {
                ballID: 100,
                time: 2285,
                x: 144.9,
                y: -327.1,
                vx: -.1,
                vy: -203.6
              }, {
                ballID: 100,
                time: 2301,
                x: 144.9,
                y: -330.6,
                vx: -.1,
                vy: -208.5
              }, {
                ballID: 201,
                time: 2302,
                x: 231.1,
                y: -486.5,
                vx: 536.9,
                vy: -1104.5
              }, {
                ballID: 200,
                time: 2302,
                x: 216.3,
                y: -456,
                vx: 68,
                vy: -118.7
              }, {
                ballID: 100,
                time: 2318,
                x: 144.9,
                y: -334.1,
                vx: -.1,
                vy: -213.1
              }, {
                ballID: 201,
                time: 2319,
                x: 240,
                y: -504.7,
                vx: 530.7,
                vy: -1091.8
              }, {
                ballID: 100,
                time: 2335,
                x: 144.9,
                y: -337.7,
                vx: -.2,
                vy: -217.2
              }, {
                ballID: 100,
                time: 2352,
                x: 144.9,
                y: -341.4,
                vx: -.2,
                vy: -221
              }, {
                ballID: 100,
                time: 2368,
                x: 144.9,
                y: -345.2,
                vx: -.2,
                vy: -224.4
              }, {
                ballID: 100,
                time: 2385,
                x: 144.9,
                y: -349,
                vx: -.2,
                vy: -227.5
              }, {
                ballID: 100,
                time: 2401,
                x: 144.9,
                y: -352.8,
                vx: -.3,
                vy: -230.2
              }, {
                ballID: 100,
                time: 2418,
                x: 144.9,
                y: -356.7,
                vx: -.3,
                vy: -232.7
              }, {
                ballID: 100,
                time: 2435,
                x: 144.9,
                y: -360.6,
                vx: -.3,
                vy: -234.8
              }, {
                ballID: 100,
                time: 2452,
                x: 144.9,
                y: -364.5,
                vx: -.3,
                vy: -236.7
              }, {
                ballID: 100,
                time: 2468,
                x: 144.9,
                y: -368.5,
                vx: -.3,
                vy: -238.3
              }, {
                ballID: 100,
                time: 2485,
                x: 144.8,
                y: -372.5,
                vx: -.3,
                vy: -239.7
              }, {
                ballID: 100,
                time: 2502,
                x: 144.8,
                y: -376.5,
                vx: -.4,
                vy: -240.9
              }, {
                ballID: 100,
                time: 2519,
                x: 144.8,
                y: -380.5,
                vx: -.4,
                vy: -241.8
              }, {
                ballID: 100,
                time: 2536,
                x: 144.8,
                y: -384.6,
                vx: -.4,
                vy: -242.5
              }, {
                ballID: 100,
                time: 2552,
                x: 144.8,
                y: -388.6,
                vx: -.4,
                vy: -243
              }, {
                ballID: 100,
                time: 2569,
                x: 144.8,
                y: -392.7,
                vx: -.4,
                vy: -243.3
              }, {
                ballID: 100,
                time: 2586,
                x: 144.8,
                y: -396.7,
                vx: -.4,
                vy: -243.5
              }, {
                ballID: 100,
                time: 2603,
                x: 144.8,
                y: -400.8,
                vx: -.4,
                vy: -243.5
              }, {
                ballID: 100,
                time: 2619,
                x: 144.8,
                y: -404.8,
                vx: -.4,
                vy: -243.3
              }, {
                ballID: 100,
                time: 2636,
                x: 144.8,
                y: -408.9,
                vx: -.4,
                vy: -243
              }, {
                ballID: 100,
                time: 2652,
                x: 144.8,
                y: -412.9,
                vx: -.4,
                vy: -242.5
              }, {
                ballID: 100,
                time: 2669,
                x: 144.8,
                y: -417,
                vx: -.4,
                vy: -241.9
              }, {
                ballID: 100,
                time: 2686,
                x: 144.8,
                y: -421,
                vx: -.4,
                vy: -241.2
              }, {
                ballID: 100,
                time: 2701,
                x: 144.8,
                y: -425,
                vx: -.4,
                vy: -240.3
              }, {
                ballID: 100,
                time: 2720,
                x: 144.8,
                y: -429,
                vx: -.4,
                vy: -239.4
              }, {
                ballID: 100,
                time: 2735,
                x: 144.8,
                y: -432.9,
                vx: -.4,
                vy: -238.3
              }, {
                ballID: 100,
                time: 2751,
                x: 144.7,
                y: -436.9,
                vx: -.4,
                vy: -237.2
              }, {
                ballID: 100,
                time: 2770,
                x: 144.7,
                y: -440.8,
                vx: -.5,
                vy: -235.9
              }, {
                ballID: 100,
                time: 2786,
                x: 144.7,
                y: -444.7,
                vx: -.5,
                vy: -234.6
              }, {
                ballID: 100,
                time: 2801,
                x: 144.7,
                y: -448.6,
                vx: -.5,
                vy: -233.2
              }, {
                ballID: 100,
                time: 2819,
                x: 144.7,
                y: -452.5,
                vx: -.5,
                vy: -231.7
              }, {
                ballID: 100,
                time: 2835,
                x: 144.7,
                y: -456.3,
                vx: -.5,
                vy: -230.1
              }, {
                ballID: 100,
                time: 2852,
                x: 144.7,
                y: -460.1,
                vx: -.5,
                vy: -228.5
              }, {
                ballID: 100,
                time: 2870,
                x: 144.7,
                y: -463.9,
                vx: -.4,
                vy: -226.8
              }, {
                ballID: 100,
                time: 2896,
                x: 144.7,
                y: -467.7,
                vx: -.4,
                vy: -225.1
              }, {
                ballID: 100,
                time: 2919,
                x: 144.7,
                y: -471.4,
                vx: -.4,
                vy: -223.3
              }, {
                ballID: 100,
                time: 2951,
                x: 144.7,
                y: -475.1,
                vx: -.4,
                vy: -221.5
              }, {
                ballID: 100,
                time: 2969,
                x: 144.7,
                y: -478.7,
                vx: -.4,
                vy: -219.6
              }, {
                ballID: 100,
                time: 2985,
                x: 144.7,
                y: -482.4,
                vx: -.4,
                vy: -217.7
              }, {
                ballID: 100,
                time: 3001,
                x: 144.7,
                y: -485.9,
                vx: -.4,
                vy: -215.7
              }, {
                ballID: 100,
                time: 3019,
                x: 144.7,
                y: -489.5,
                vx: -.4,
                vy: -213.8
              }, {
                ballID: 100,
                time: 3035,
                x: 144.6,
                y: -493,
                vx: -.4,
                vy: -211.7
              }, {
                ballID: 100,
                time: 3052,
                x: 144.6,
                y: -493.9,
                vx: -.4,
                vy: 148.8
              }, {
                ballID: 100,
                time: 3068,
                x: 144.6,
                y: -491.5,
                vx: -.4,
                vy: 145.5
              }, {
                ballID: 100,
                time: 3085,
                x: 144.6,
                y: -489.1,
                vx: -.4,
                vy: 142.4
              }, {
                ballID: 100,
                time: 3103,
                x: 144.6,
                y: -486.8,
                vx: -.4,
                vy: 139.3
              }, {
                ballID: 100,
                time: 3118,
                x: 144.6,
                y: -484.5,
                vx: -.4,
                vy: 136.3
              }, {
                ballID: 100,
                time: 3134,
                x: 144.6,
                y: -482.3,
                vx: -.4,
                vy: 133.3
              }, {
                ballID: 100,
                time: 3151,
                x: 144.6,
                y: -480.1,
                vx: -.4,
                vy: 130.5
              }, {
                ballID: 100,
                time: 3167,
                x: 144.6,
                y: -478,
                vx: -.4,
                vy: 127.7
              }, {
                ballID: 100,
                time: 3185,
                x: 144.6,
                y: -475.9,
                vx: -.4,
                vy: 125
              }, {
                ballID: 100,
                time: 3202,
                x: 144.6,
                y: -473.9,
                vx: -.3,
                vy: 122.3
              }, {
                ballID: 100,
                time: 3217,
                x: 144.6,
                y: -471.9,
                vx: -.3,
                vy: 119.7
              }, {
                ballID: 100,
                time: 3235,
                x: 144.6,
                y: -469.9,
                vx: -.3,
                vy: 117.2
              }, {
                ballID: 100,
                time: 3252,
                x: 144.6,
                y: -468,
                vx: -.3,
                vy: 114.8
              }, {
                ballID: 100,
                time: 3268,
                x: 144.6,
                y: -466.1,
                vx: -.3,
                vy: 112.4
              }, {
                ballID: 100,
                time: 3286,
                x: 144.6,
                y: -464.3,
                vx: -.3,
                vy: 110.1
              }, {
                ballID: 100,
                time: 3301,
                x: 144.6,
                y: -462.5,
                vx: -.3,
                vy: 107.8
              }, {
                ballID: 100,
                time: 3319,
                x: 144.6,
                y: -460.8,
                vx: -.3,
                vy: 105.6
              }, {
                ballID: 100,
                time: 3335,
                x: 144.6,
                y: -459,
                vx: -.3,
                vy: 103.4
              }, {
                ballID: 100,
                time: 3352,
                x: 144.6,
                y: -457.3,
                vx: -.3,
                vy: 101.3
              }, {
                ballID: 100,
                time: 3369,
                x: 144.6,
                y: -455.7,
                vx: -.3,
                vy: 99.3
              }, {
                ballID: 100,
                time: 3384,
                x: 144.5,
                y: -454.1,
                vx: -.3,
                vy: 97.2
              }, {
                ballID: 100,
                time: 3402,
                x: 144.5,
                y: -452.5,
                vx: -.3,
                vy: 95.3
              }, {
                ballID: 100,
                time: 3419,
                x: 144.5,
                y: -450.9,
                vx: -.3,
                vy: 93.4
              }, {
                ballID: 100,
                time: 3435,
                x: 144.5,
                y: -449.4,
                vx: -.3,
                vy: 91.5
              }, {
                ballID: 100,
                time: 3452,
                x: 144.5,
                y: -447.9,
                vx: -.3,
                vy: 89.7
              }, {
                ballID: 100,
                time: 3469,
                x: 144.5,
                y: -446.4,
                vx: -.3,
                vy: 87.9
              }, {
                ballID: 100,
                time: 3485,
                x: 144.5,
                y: -445,
                vx: -.2,
                vy: 86.2
              }, {
                ballID: 100,
                time: 3502,
                x: 144.5,
                y: -443.6,
                vx: -.2,
                vy: 84.5
              }, {
                ballID: 100,
                time: 3519,
                x: 144.5,
                y: -442.2,
                vx: -.2,
                vy: 82.8
              }, {
                ballID: 100,
                time: 3536,
                x: 144.5,
                y: -440.9,
                vx: -.2,
                vy: 81.2
              }, {
                ballID: 100,
                time: 3551,
                x: 144.5,
                y: -439.5,
                vx: -.2,
                vy: 79.6
              }, {
                ballID: 100,
                time: 3568,
                x: 144.5,
                y: -438.2,
                vx: -.2,
                vy: 78.1
              }, {
                ballID: 100,
                time: 3586,
                x: 144.5,
                y: -436.9,
                vx: -.2,
                vy: 76.5
              }, {
                ballID: 100,
                time: 3603,
                x: 144.5,
                y: -435.7,
                vx: -.2,
                vy: 75.1
              }, {
                ballID: 100,
                time: 3618,
                x: 144.5,
                y: -434.5,
                vx: -.2,
                vy: 73.6
              }, {
                ballID: 100,
                time: 3635,
                x: 144.5,
                y: -433.3,
                vx: -.2,
                vy: 72.2
              }, {
                ballID: 100,
                time: 3651,
                x: 144.5,
                y: -432.1,
                vx: -.2,
                vy: 70.8
              }, {
                ballID: 100,
                time: 3668,
                x: 144.5,
                y: -430.9,
                vx: -.2,
                vy: 69.5
              }, {
                ballID: 100,
                time: 3686,
                x: 144.5,
                y: -429.8,
                vx: -.2,
                vy: 68.1
              }, {
                ballID: 100,
                time: 3701,
                x: 144.5,
                y: -428.7,
                vx: -.2,
                vy: 66.9
              }, {
                ballID: 100,
                time: 3719,
                x: 144.5,
                y: -427.6,
                vx: -.2,
                vy: 65.6
              }, {
                ballID: 100,
                time: 3735,
                x: 144.5,
                y: -426.5,
                vx: -.2,
                vy: 64.4
              }, {
                ballID: 100,
                time: 3752,
                x: 144.5,
                y: -425.4,
                vx: -.2,
                vy: 63.1
              }, {
                ballID: 100,
                time: 3769,
                x: 144.5,
                y: -424.4,
                vx: -.2,
                vy: 62
              }, {
                ballID: 100,
                time: 3785,
                x: 144.5,
                y: -423.4,
                vx: -.2,
                vy: 60.8
              }, {
                ballID: 100,
                time: 3802,
                x: 144.5,
                y: -422.4,
                vx: -.2,
                vy: 59.7
              }, {
                ballID: 100,
                time: 3818,
                x: 144.5,
                y: -421.4,
                vx: -.2,
                vy: 58.6
              }, {
                ballID: 100,
                time: 3835,
                x: 144.5,
                y: -420.5,
                vx: -.2,
                vy: 57.5
              }, {
                ballID: 100,
                time: 3851,
                x: 144.5,
                y: -419.5,
                vx: -.2,
                vy: 56.4
              }, {
                ballID: 100,
                time: 3869,
                x: 144.5,
                y: -418.6,
                vx: -.2,
                vy: 55.4
              }, {
                ballID: 100,
                time: 3885,
                x: 144.5,
                y: -417.7,
                vx: -.2,
                vy: 54.3
              }, {
                ballID: 100,
                time: 3902,
                x: 144.5,
                y: -416.8,
                vx: -.2,
                vy: 53.3
              }, {
                ballID: 100,
                time: 3919,
                x: 144.5,
                y: -415.9,
                vx: -.2,
                vy: 52.4
              }, {
                ballID: 100,
                time: 3935,
                x: 144.5,
                y: -415.1,
                vx: -.2,
                vy: 51.4
              }, {
                ballID: 100,
                time: 3952,
                x: 144.5,
                y: -414.2,
                vx: -.2,
                vy: 50.5
              }, {
                ballID: 100,
                time: 3968,
                x: 144.5,
                y: -413.4,
                vx: -.2,
                vy: 49.5
              }, {
                ballID: 100,
                time: 3985,
                x: 144.5,
                y: -412.6,
                vx: -.2,
                vy: 48.6
              }, {
                ballID: 100,
                time: 4002,
                x: 144.5,
                y: -411.8,
                vx: -.2,
                vy: 47.8
              }, {
                ballID: 100,
                time: 4019,
                x: 144.5,
                y: -411,
                vx: -.2,
                vy: 46.9
              }, {
                ballID: 100,
                time: 4035,
                x: 144.4,
                y: -410.3,
                vx: -.2,
                vy: 46.1
              }, {
                ballID: 100,
                time: 4052,
                x: 144.4,
                y: -409.5,
                vx: -.1,
                vy: 45.2
              }, {
                ballID: 100,
                time: 4068,
                x: 144.4,
                y: -408.8,
                vx: -.1,
                vy: 44.4
              }, {
                ballID: 100,
                time: 4086,
                x: 144.4,
                y: -408,
                vx: -.1,
                vy: 43.6
              }, {
                ballID: 100,
                time: 4102,
                x: 144.4,
                y: -407.3,
                vx: -.1,
                vy: 42.8
              }, {
                ballID: 100,
                time: 4119,
                x: 144.4,
                y: -406.6,
                vx: -.1,
                vy: 42.1
              }, {
                ballID: 100,
                time: 4135,
                x: 144.4,
                y: -405.9,
                vx: -.1,
                vy: 41.3
              }, {
                ballID: 100,
                time: 4153,
                x: 144.4,
                y: -405.2,
                vx: -.1,
                vy: 40.6
              }, {
                ballID: 100,
                time: 4169,
                x: 144.4,
                y: -404.6,
                vx: -.1,
                vy: 39.9
              }, {
                ballID: 100,
                time: 4187,
                x: 144.4,
                y: -403.9,
                vx: -.1,
                vy: 39.2
              }, {
                ballID: 100,
                time: 4203,
                x: 144.4,
                y: -403.3,
                vx: -.1,
                vy: 38.5
              }, {
                ballID: 100,
                time: 4219,
                x: 144.4,
                y: -402.7,
                vx: -.1,
                vy: 37.8
              }, {
                ballID: 100,
                time: 4236,
                x: 144.4,
                y: -402,
                vx: -.1,
                vy: 37.1
              }, {
                ballID: 100,
                time: 4254,
                x: 144.4,
                y: -401.4,
                vx: -.1,
                vy: 36.5
              }, {
                ballID: 100,
                time: 4269,
                x: 144.4,
                y: -400.8,
                vx: -.1,
                vy: 35.8
              }, {
                ballID: 100,
                time: 4286,
                x: 144.4,
                y: -400.2,
                vx: -.1,
                vy: 35.2
              }, {
                ballID: 100,
                time: 4302,
                x: 144.4,
                y: -399.7,
                vx: -.1,
                vy: 34.6
              }, {
                ballID: 100,
                time: 4319,
                x: 144.4,
                y: -399.1,
                vx: -.1,
                vy: 34
              }, {
                ballID: 100,
                time: 4336,
                x: 144.4,
                y: -398.5,
                vx: -.1,
                vy: 33.4
              }, {
                ballID: 100,
                time: 4352,
                x: 144.4,
                y: -398,
                vx: -.1,
                vy: 32.8
              }, {
                ballID: 100,
                time: 4369,
                x: 144.4,
                y: -397.5,
                vx: -.1,
                vy: 32.2
              }, {
                ballID: 100,
                time: 4386,
                x: 144.4,
                y: -396.9,
                vx: -.1,
                vy: 31.6
              }, {
                ballID: 100,
                time: 4402,
                x: 144.4,
                y: -396.4,
                vx: -.1,
                vy: 31.1
              }, {
                ballID: 100,
                time: 4419,
                x: 144.4,
                y: -395.9,
                vx: -.1,
                vy: 30.6
              }, {
                ballID: 100,
                time: 4436,
                x: 144.4,
                y: -395.4,
                vx: -.1,
                vy: 30
              }, {
                ballID: 100,
                time: 4453,
                x: 144.4,
                y: -394.9,
                vx: -.1,
                vy: 29.5
              }, {
                ballID: 100,
                time: 4470,
                x: 144.4,
                y: -394.4,
                vx: -.1,
                vy: 29
              }, {
                ballID: 100,
                time: 4485,
                x: 144.4,
                y: -393.9,
                vx: -.1,
                vy: 28.5
              }, {
                ballID: 100,
                time: 4503,
                x: 144.4,
                y: -393.5,
                vx: -.1,
                vy: 28
              }, {
                ballID: 100,
                time: 4518,
                x: 144.4,
                y: -393,
                vx: -.1,
                vy: 27.5
              }, {
                ballID: 100,
                time: 4536,
                x: 144.4,
                y: -392.6,
                vx: -.1,
                vy: 27
              }, {
                ballID: 100,
                time: 4553,
                x: 144.4,
                y: -392.1,
                vx: -.1,
                vy: 26.6
              }, {
                ballID: 100,
                time: 4568,
                x: 144.4,
                y: -391.7,
                vx: -.1,
                vy: 26.1
              }, {
                ballID: 100,
                time: 4586,
                x: 144.4,
                y: -391.3,
                vx: -.1,
                vy: 25.7
              }, {
                ballID: 100,
                time: 4602,
                x: 144.4,
                y: -390.8,
                vx: -.1,
                vy: 25.2
              }, {
                ballID: 100,
                time: 4619,
                x: 144.4,
                y: -390.4,
                vx: -.1,
                vy: 24.8
              }, {
                ballID: 100,
                time: 4636,
                x: 144.4,
                y: -390,
                vx: -.1,
                vy: 24.4
              }, {
                ballID: 100,
                time: 4652,
                x: 144.4,
                y: -389.6,
                vx: -.1,
                vy: 24
              }, {
                ballID: 100,
                time: 4668,
                x: 144.4,
                y: -389.2,
                vx: -.1,
                vy: 23.5
              }, {
                ballID: 100,
                time: 4686,
                x: 144.4,
                y: -388.8,
                vx: -.1,
                vy: 23.1
              }, {
                ballID: 100,
                time: 4702,
                x: 144.4,
                y: -388.5,
                vx: -.1,
                vy: 22.7
              }, {
                ballID: 100,
                time: 4719,
                x: 144.4,
                y: -388.1,
                vx: -.1,
                vy: 22.4
              }, {
                ballID: 100,
                time: 4736,
                x: 144.4,
                y: -387.7,
                vx: -.1,
                vy: 22
              }, {
                ballID: 100,
                time: 4753,
                x: 144.4,
                y: -387.4,
                vx: -.1,
                vy: 21.6
              }, {
                ballID: 100,
                time: 4768,
                x: 144.4,
                y: -387,
                vx: -.1,
                vy: 21.2
              }, {
                ballID: 100,
                time: 4786,
                x: 144.4,
                y: -386.7,
                vx: -.1,
                vy: 20.9
              }, {
                ballID: 100,
                time: 4802,
                x: 144.4,
                y: -386.3,
                vx: -.1,
                vy: 20.5
              }, {
                ballID: 100,
                time: 4818,
                x: 144.4,
                y: -386,
                vx: -.1,
                vy: 20.2
              }, {
                ballID: 100,
                time: 4836,
                x: 144.4,
                y: -385.6,
                vx: -.1,
                vy: 19.8
              }, {
                ballID: 100,
                time: 4854,
                x: 144.4,
                y: -385.3,
                vx: -.1,
                vy: 19.5
              }, {
                ballID: 100,
                time: 4869,
                x: 144.4,
                y: -385,
                vx: -.1,
                vy: 19.2
              }, {
                ballID: 100,
                time: 4885,
                x: 144.4,
                y: -384.7,
                vx: -.1,
                vy: 18.8
              }, {
                ballID: 100,
                time: 4902,
                x: 144.4,
                y: -384.4,
                vx: -.1,
                vy: 18.5
              }, {
                ballID: 100,
                time: 4918,
                x: 144.4,
                y: -384.1,
                vx: -.1,
                vy: 18.2
              }, {
                ballID: 100,
                time: 4935,
                x: 144.4,
                y: -383.8,
                vx: -.1,
                vy: 17.9
              }, {
                ballID: 100,
                time: 4952,
                x: 144.4,
                y: -383.5,
                vx: -.1,
                vy: 17.6
              }, {
                ballID: 100,
                time: 4996,
                x: 144.4,
                y: -383.2,
                vx: -.1,
                vy: 17.3
              }, {
                ballID: 100,
                time: 5025,
                x: 144.4,
                y: -382.9,
                vx: -.1,
                vy: 17
              }, {
                ballID: 100,
                time: 5035,
                x: 144.4,
                y: -382.6,
                vx: -.1,
                vy: 16.7
              }, {
                ballID: 100,
                time: 5319,
                x: 144.4,
                y: -378.7,
                vx: 0,
                vy: 0
              }],
              des: [{
                ballID: 201,
                time: 2837
              }, {
                ballID: 200,
                time: 3268
              }]
            }]
          },
          mvCompress: 0,
          time: "2019-11-30 19:33:42"
        }, {
          tableInfo: {
            tableID: 18,
            sID: 18,
            name: "username-1",
            time: 1573359932758,
            balls: [{
              ballID: 200,
              ballType: 2,
              x: 6,
              y: -257,
              tx1: 0,
              tx2: 0,
              ballMatIdx: 5,
              p1: 0,
              p2: 0,
              p3: 0
            }, {
              ballID: 201,
              ballType: 2,
              x: 40,
              y: -236,
              tx1: 0,
              tx2: 0,
              ballMatIdx: 2,
              p1: 0,
              p2: 0,
              p3: 0
            }, {
              ballID: 100,
              ballType: 1,
              x: 194,
              y: -154,
              tx1: 0,
              tx2: 0,
              ballMatIdx: 0,
              p1: 0,
              p2: 0,
              p3: 0
            }],
            condition: {
              type: 1,
              cdBalls: [{
                ballMatIdx: 5,
                ballType: 2,
                ballNum: 0,
                p1: 0,
                p2: 0
              }, {
                ballMatIdx: 2,
                ballType: 2,
                ballNum: 0,
                p1: 0,
                p2: 0
              }],
              lHallID: [],
              ganNum: 1,
              p1: 0,
              p2: 0
            },
            cue: {
              cueID: 0,
              Mat: 0,
              p1: 0,
              p2: 0
            },
            isPass: 0,
            tableMat: 0,
            color: "6",
            particle: "2",
            p1: 0,
            p2: 0,
            p3: 0
          },
          mv: {
            balls: [{
              ballID: 200,
              ballType: 2,
              ballMatIdx: 5,
              x: 6,
              y: -257
            }, {
              ballID: 201,
              ballType: 2,
              ballMatIdx: 2,
              x: 40,
              y: -236
            }, {
              ballID: 100,
              ballType: 1,
              ballMatIdx: 0,
              x: 194,
              y: -154
            }],
            cues: [{
              hit: {
                rad: 55884,
                power: 89,
                time: 9879,
                radAngle: 0,
                radVx: 0,
                radVy: 0
              },
              moves: [{
                ballID: 100,
                time: 2004,
                x: 194,
                y: -154,
                vx: -2186.4,
                vy: -1367.3
              }, {
                ballID: 100,
                time: 2021,
                x: 158.1,
                y: -176.5,
                vx: -2150.5,
                vy: -1344.8
              }, {
                ballID: 100,
                time: 2071,
                x: 69.3,
                y: -239.5,
                vx: 11.1,
                vy: -1008.5
              }, {
                ballID: 201,
                time: 2071,
                x: 26.7,
                y: -236.4,
                vx: -900.2,
                vy: 755.5
              }, {
                ballID: 200,
                time: 2071,
                x: 4.1,
                y: -258.7,
                vx: -1157.5,
                vy: -1026.9
              }, {
                ballID: 201,
                time: 2089,
                x: 11.8,
                y: -223.9,
                vx: -889.8,
                vy: 746.8
              }, {
                ballID: 200,
                time: 2089,
                x: -15,
                y: -275.6,
                vx: -1144.1,
                vy: -1015.1
              }, {
                ballID: 200,
                time: 2305,
                x: -240.6,
                y: -478.6,
                vx: 787.1,
                vy: -873
              }, {
                ballID: 200,
                time: 2337,
                x: -215.6,
                y: -484.7,
                vx: 715.1,
                vy: 727.7
              }, {
                ballID: 100,
                time: 2371,
                x: 72.1,
                y: -491.5,
                vx: 8.2,
                vy: 666.5
              }, {
                ballID: 100,
                time: 6356,
                x: 80.2,
                y: 162.2,
                vx: 0,
                vy: 0
              }],
              des: [{
                ballID: 201,
                time: 2938
              }, {
                ballID: 200,
                time: 3722
              }]
            }]
          },
          mvCompress: 0,
          time: "2019-11-30 22:46:08"
        }, {
          tableInfo: {
            tableID: 19,
            sID: 19,
            name: "username-1",
            time: 1573359932758,
            balls: [{
              ballID: 200,
              ballType: 2,
              x: 183,
              y: 279,
              tx1: 0,
              tx2: 0,
              ballMatIdx: 5,
              p1: 0,
              p2: 0,
              p3: 0
            }, {
              ballID: 201,
              ballType: 2,
              x: 229,
              y: 467,
              tx1: 0,
              tx2: 0,
              ballMatIdx: 2,
              p1: 0,
              p2: 0,
              p3: 0
            }, {
              ballID: 100,
              ballType: 1,
              x: -2,
              y: -78,
              tx1: 0,
              tx2: 0,
              ballMatIdx: 0,
              p1: 0,
              p2: 0,
              p3: 0
            }],
            condition: {
              type: 1,
              cdBalls: [{
                ballMatIdx: 5,
                ballType: 2,
                ballNum: 0,
                p1: 0,
                p2: 0
              }, {
                ballMatIdx: 2,
                ballType: 2,
                ballNum: 0,
                p1: 0,
                p2: 0
              }],
              lHallID: [],
              ganNum: 1,
              p1: 0,
              p2: 0
            },
            cue: {
              cueID: 0,
              Mat: 0,
              p1: 0,
              p2: 0
            },
            isPass: 0,
            tableMat: 0,
            color: "6",
            particle: "2",
            p1: 0,
            p2: 0,
            p3: 0
          },
          mv: {
            balls: [{
              ballID: 200,
              ballType: 2,
              ballMatIdx: 5,
              x: 183,
              y: 279
            }, {
              ballID: 201,
              ballType: 2,
              ballMatIdx: 2,
              x: 229,
              y: 467
            }, {
              ballID: 100,
              ballType: 1,
              ballMatIdx: 0,
              x: -2,
              y: -78
            }],
            cues: [{
              hit: {
                rad: -206719,
                power: 100,
                time: 6452,
                radAngle: 0,
                radVx: 0,
                radVy: 0
              },
              moves: [{
                ballID: 100,
                time: 2006,
                x: -2,
                y: -78,
                vx: 1379.8,
                vy: 2547.6
              }, {
                ballID: 100,
                time: 2024,
                x: 20.6,
                y: -36.3,
                vx: 1357.2,
                vy: 2505.8
              }, {
                ballID: 100,
                time: 2158,
                x: 182.4,
                y: 248.7,
                vx: 609.4,
                vy: -150.6
              }, {
                ballID: 200,
                time: 2158,
                x: 189.2,
                y: 304.3,
                vx: 579.6,
                vy: 2346
              }, {
                ballID: 200,
                time: 2174,
                x: 198.8,
                y: 343,
                vx: 572.9,
                vy: 2319
              }, {
                ballID: 201,
                time: 2223,
                x: 232.7,
                y: 483.3,
                vx: 467.7,
                vy: 2022.7
              }, {
                ballID: 200,
                time: 2224,
                x: 223,
                y: 440,
                vx: 85.5,
                vy: 216.9
              }, {
                ballID: 201,
                time: 2241,
                x: 249.7,
                y: 509.8,
                vx: 1627.3,
                vy: 1154.6
              }, {
                ballID: 100,
                time: 2274,
                x: 230.9,
                y: 232.3,
                vx: -542.9,
                vy: -134.2
              }, {
                ballID: 200,
                time: 2458,
                x: 240.8,
                y: 486.5,
                vx: 43.7,
                vy: 191
              }, {
                ballID: 100,
                time: 4324,
                x: -238.5,
                y: 115.7,
                vx: 71,
                vy: -17.6
              }, {
                ballID: 100,
                time: 6074,
                x: -180,
                y: 101.2,
                vx: 0,
                vy: 0
              }],
              des: [{
                ballID: 201,
                time: 2759
              }, {
                ballID: 200,
                time: 3041
              }]
            }]
          },
          mvCompress: 0,
          time: "2019-12-01 19:41:31"
        }, {
          tableInfo: {
            tableID: 20,
            sID: 20,
            name: "username-1",
            time: 1573359932758,
            balls: [{
              ballID: 200,
              ballType: 2,
              x: -39,
              y: 489,
              tx1: 0,
              tx2: 0,
              ballMatIdx: 3,
              p1: 0,
              p2: 0,
              p3: 0
            }, {
              ballID: 201,
              ballType: 2,
              x: -162,
              y: 493,
              tx1: 0,
              tx2: 0,
              ballMatIdx: 2,
              p1: 0,
              p2: 0,
              p3: 0
            }, {
              ballID: 100,
              ballType: 1,
              x: 120,
              y: 488,
              tx1: 0,
              tx2: 0,
              ballMatIdx: 0,
              p1: 0,
              p2: 0,
              p3: 0
            }],
            condition: {
              type: 1,
              cdBalls: [{
                ballMatIdx: 3,
                ballType: 2,
                ballNum: 0,
                p1: 0,
                p2: 0
              }, {
                ballMatIdx: 2,
                ballType: 2,
                ballNum: 0,
                p1: 0,
                p2: 0
              }],
              lHallID: [],
              ganNum: 1,
              p1: 0,
              p2: 0
            },
            cue: {
              cueID: 0,
              Mat: 0,
              p1: 0,
              p2: 0
            },
            isPass: 0,
            tableMat: 0,
            color: "6",
            particle: "2",
            p1: 0,
            p2: 0,
            p3: 0
          },
          mv: {
            balls: [{
              ballID: 200,
              ballType: 2,
              ballMatIdx: 3,
              x: -39,
              y: 489
            }, {
              ballID: 201,
              ballType: 2,
              ballMatIdx: 2,
              x: -162,
              y: 493
            }, {
              ballID: 100,
              ballType: 1,
              ballMatIdx: 0,
              x: 120,
              y: 488
            }],
            cues: [{
              hit: {
                rad: -29,
                power: 77,
                time: 5572,
                radAngle: 0,
                radVx: 0,
                radVy: 0
              },
              moves: [{
                ballID: 100,
                time: 2014,
                x: 120,
                y: 488,
                vx: -2231,
                vy: .6
              }, {
                ballID: 100,
                time: 2031,
                x: 83.4,
                y: 488,
                vx: -2194.4,
                vy: .6
              }, {
                ballID: 100,
                time: 2081,
                x: -10.9,
                y: 487.6,
                vx: -210.9,
                vy: -61.3
              }, {
                ballID: 200,
                time: 2083,
                x: -50.9,
                y: 489.3,
                vx: -1877.4,
                vy: 61.8
              }, {
                ballID: 200,
                time: 2098,
                x: -81.9,
                y: 490.4,
                vx: -1855.8,
                vy: 61.1
              }, {
                ballID: 201,
                time: 2131,
                x: -171.1,
                y: 493.2,
                vx: -1632,
                vy: 50.7
              }, {
                ballID: 200,
                time: 2131,
                x: -133.6,
                y: 492.1,
                vx: -181.3,
                vy: 9
              }, {
                ballID: 201,
                time: 2147,
                x: -198,
                y: 494.1,
                vx: -1613.2,
                vy: 50.1
              }, {
                ballID: 201,
                time: 2181,
                x: -250.9,
                y: 494.2,
                vx: -1576.2,
                vy: -39.3
              }, {
                ballID: 201,
                time: 2197,
                x: -267.6,
                y: 507.3,
                vx: 1053.5,
                vy: 782.8
              }, {
                ballID: 200,
                time: 2448,
                x: -184.8,
                y: 494.5,
                vx: -145.4,
                vy: 0
              }, {
                ballID: 200,
                time: 3014,
                x: -252.3,
                y: 495,
                vx: -90.5,
                vy: 26.2
              }, {
                ballID: 100,
                time: 4947,
                x: -209.5,
                y: 429.9,
                vx: 0,
                vy: 0
              }],
              des: [{
                ballID: 201,
                time: 2715
              }, {
                ballID: 200,
                time: 3532
              }]
            }]
          },
          mvCompress: 0,
          time: "2019-12-01 20:48:28"
        }]
      }
    };
    cc._RF.pop();
