export class GVYOSIN {
    static ZRXAERRUGNSM = "1.5.0";
    static OFBTDJQFN = 6;
    static MDOKKVQUSOZBUD = "yy.dc.bt";
    static MILTNZ = "cc.CallbackManager.HDIRISZ";
    static PGQSCYPDMUTK = "AYQCMM";
    static RVIUIWJHMUDCSKSL = "dliweet";
    static UPJRPLSXMB = "fqfaq";
    static XUMCMXUBF = "g";
    static YLRFVCYCCCYL = "eb";
    static PENETODX = "bcd";
    static APNFOB = "i";
    static EBTJYCXYIDHWS = "ci";
    static UBWNMRTPEYNSRW = "jjviuxh";
    static ENFYLZFAPPIG = "mvqzdj";
    static XTXPMOKCNXI = "rmkmle";
    static YRNGADCWZXK = "ayip";
    static ILGPNHKCNXFIPD = "jmtsmib";
    static XPXGZHQTLFKOPTQV = "azkab";
    static IMYDTQP = "jmfpmdk";
    static WOCPZPIRLYBI = "gtiph";
    static PQTDBKYXIR = "lzicdd";
    static KAAPHLHD = "khw";
}
