export interface BusinessRequestDescriptor {
    uri: string;
    enqueue: boolean;
}

export const BUSINESS_REQUEST_DESCRIPTORS: Record<string, BusinessRequestDescriptor> = {
    config: { uri: "AfBJn/config", enqueue: false },
    WithdrawInfo: { uri: "LcmMRi/BYqawo", enqueue: false },
    WithdrawCash: { uri: "LcmMRi/ZworCc", enqueue: false },
    BindTxAccount: { uri: "LcmMRi/arHKkf", enqueue: false },
    BarrageList: { uri: "YZCUIm/PqyICJ", enqueue: false },
    WithdrawChannels: { uri: "c_l", enqueue: false },
    VerifyBindInfo: { uri: "ck_i", enqueue: false },
    auto_submit: { uri: "mOIrra/GwJUnl", enqueue: false },
    TouristLogin: { uri: "mOIrra/VfVrta", enqueue: false },
    FirebaseToken: { uri: "YZCUIm/KJvhdv", enqueue: false },
    ExtractFundDashboard: { uri: "mpbc/seotms", enqueue: false },
    ExtractCashDashboard: { uri: "mpbc/awy", enqueue: false },
    ExtractCashRecord: { uri: "mpbc/ykr", enqueue: false },
    ExtractFundRecord: { uri: "mpbc/ykr", enqueue: false },
    ExtractCash: { uri: "mpbc/fhfgrp", enqueue: false },
    BindTx: { uri: "mpbc/dycdds", enqueue: false },
    GetGameConfig: { uri: "AfBJn/getGameConfig", enqueue: false },
    ArrowLevelConfig: { uri: "xKmD9w/QrLv7n", enqueue: false },
    ArrowConsumeProp: { uri: "xKmD9w/pUsH3k", enqueue: false },
    ArrowRewardSettle: { uri: "ehwqDl/tMvhRC", enqueue: false },
    ArrowClaimReward: { uri: "ehwqDl/CCDFGN", enqueue: false },
    ArrowClaimAdReward: { uri: "vNZlOY/KWcPza", enqueue: false },
    UserInfo: { uri: "YZCUIm/MgQDzj", enqueue: false },
    AdMake: { uri: "pbou/zrbjwl", enqueue: false },
    BubbleInfo: { uri: "pbou/jlyt", enqueue: false },
    RankInfo: { uri: "pbou/ggvhxb", enqueue: false },
    ScrollMsg: { uri: "pbou/fthco", enqueue: false },
    StartGame: { uri: "pbou/wkin", enqueue: false },
    SubmitGame: { uri: "pbou/vwah", enqueue: false },
    LuckyReward: { uri: "pbou/lroljc", enqueue: false },
    RefreshBlock: { uri: "pbou/gnnxx", enqueue: false },
    GuideUpdate: { uri: "pbou/myjc", enqueue: false },
    OverGame: { uri: "pbou/jldqkh", enqueue: false },
    HotUpdate: { uri: "lpzvzk", enqueue: false },
    GuideReward: { uri: "pbou/lttxwr", enqueue: false },
    NotifyDec: { uri: "pbou/pxv", enqueue: false },
    TaskInfo: { uri: "YZCUIm/UCNZBa", enqueue: false },
    TaskShowReward: { uri: "YZCUIm/PpAmkA", enqueue: false },
    TaskOnlyReward: { uri: "YZCUIm/PpAmkA", enqueue: false },
};
